name: "Publish"
on:
  # Run only when pushing to master branch
  push:
    branches:
      - master
jobs:
  emanote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build emanote site 🔧
        run: |
          mkdir -p output.docker
          docker run -v $PWD:/data sridca/emanote emanote --layers /data gen /data/output.docker
          cp -r output.docker output  # Ditch docker created root-owned files
          bash output/_emanote-bin/compile-css
      - name: Deploy to gh-pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output/
          cname: zimbatm.com
